### PR TITLE
GTK3.18, GTK3.20, Metacity - Titlebar and headerbar colors vary with focus

### PR DESCRIPTION
**Pull request by smurphos**
2nd attempt..... ;-). I've created a clone repo now for my other tweaking - should be no more accidental PRs.

So I've reworked my original attempt at this and tested with my 8 color variations (some dark, some quite light) and the 4 test themes (clearlooks, monovedek etc) and the results all look quite nice.

I did get rid of the GTK3.20 use of the chose contrast function in the process.....I don't think it's needed given the initial definitions of titlebar_fg_focused and titlebar_fg_unfocused

### CODE REVIEW

**Comment by smurphos** [comment]
So I guess the screenshot comparison failure is to be expected given the PR slightly changes the standard color of the metacity icons (and title) for any given theme.

**Comment by actionless** [comment]
thanks! looks good so far

here you can see how to update the screenshots used for tests:
https://github.com/actionless/oomox-gtk-theme#hacking

**Comment by actionless** [comment]
By the way, i also saw your Cinnamon theme. Good job on it.
I was thinking what currently oomox-gtk-theme is missing a cinnamon theme so later on you could adapt yours to be generated together with gtk themes but follow ROUNDNESS and GRADIENT settings from oomox and i would suggest lowering down the borders contrast (to look about the same as in gtk themes)

**Comment by actionless** [comment]
hi! do you need any help with generating the screenshots?

**Comment by smurphos** [comment]
Nope. I did have to temporarily comment out some of the checks in the test script to get it to run through and create screenshots for color files I'd added to the test directory that didn't have a current screenshot.  Looking at the commit history I think it is supposed to work around missing screenshots but that isn't happening - it stalls after creating the first screenshot.

I'm making a start on a scss template for a cinnamon theme. I'll give you a shout when I've got something working for you to review before PR.  Probably in a week or two.

**Comment by actionless** [comment]
i think it will be easier to merge smaller pull requests so in scope of this one it will be enough just to re-generate the screenshots to get it merged

**Comment by smurphos** [comment]
Ahh - I'd misunderstood that you needed updated screenshots to merge. I'd been struggling with the test suite trying to get it to conduct tests and generate for additional color files added in my cloned repo.

Anyway I've generated and committed updated screenshots for this branch.....and the build checks have passed.

**Comment by actionless** [comment]
> I'd been struggling with the test suite trying to get it to conduct tests and generate for additional color files added in my cloned repo.

please create a separate ticket and supply the inputs and logs so i can reproduce it, shouldn't be something complicated to fix/clarify

**Comment by actionless** [comment]
thanks for preparing this changeset!

**Comment by actionless** [comment]
i did some more changes, so now Cinnamon theme can be exported from oomox gui and listed in capabilities

**Comment by smurphos** [comment]
Yikes - you will want to remove the cinnamon stuff. It's definitely not ready for prime-time yet. Did not intend to include it in that commit.

**Comment by smurphos** [comment]
Thanks - it'll be a week or two.

**Pull request merged**
